### PR TITLE
upload first xlsform 

### PR DESCRIPTION
**Pull request by danielduhh**
Uploading the first xls form in /forms directory throws .forEach not a function error. 
This makes sure `result.xforms.xform` is an array

### CODE REVIEW

**Comment by hallahan** [comment]
@danielduhh - What is different about how you are uploading the xlsx file from before? What action creates this error?

**Comment by danielduhh** [comment]
@hallahan Not sure whats different.. However, when I installed OMK Server from scratch with no data, this error occurred

**Comment by hallahan** [comment]
OK, I'll give your change a try and merge if it is fine. It shouldn't change existing behavior, so we're probably ok.

**Comment by hallahan** [comment]
Works. Merging!

**Pull request merged**
